modulelobby.res = {
    fonts_font : "res/fonts/tengxiangyuan.ttf",
    artnum_270x41 : "res/ui/artnum/270x41.png",
    artnum_312x33_shop : "res/ui/artnum/312x33_shop.png",
    artnum_336x32_rank : "res/ui/artnum/336x32_rank.png",
    artnum_384x42_game : "res/ui/artnum/384x42_game.png",
    artnum_384x42_shop : "res/ui/artnum/384x42_shop.png",
    artnum_432x47_dow_shop : "res/ui/artnum/432x47_dow.png",
    //config
    config_component : "res/config/component.json",
    config_com_4 : "res/config/com_4.json",
    config_com_4_manifest : "res/config/com_4_manifest.json",
    config_com_6 : "res/config/com_6.json",
    config_com_6_manifest : "res/config/com_6_manifest.json",
    config_com_7 : "res/config/com_7.json",
    config_com_7_manifest : "res/config/com_7_manifest.json",
    config_com_8 : "res/config/com_8.json",
    config_com_8_manifest : "res/config/com_8_manifest.json",
    config_com_9 : "res/config/com_9.json",
    config_com_9_manifest : "res/config/com_9_manifest.json",
    config_com_10 : "res/config/com_10.json",
    config_com_10_manifest : "res/config/com_10_manifest.json",
    config_com_12 : "res/config/com_12.json",
    config_com_12_manifest : "res/config/com_12_manifest.json",
    config_com_13 : "res/config/com_13.json",
    config_com_13_manifest : "res/config/com_13_manifest.json",
    config_shieldwords : "res/config/shieldwords.json",
    config_serverconfig : "res/config/serverconfig.json",
    //icon
    icon_qrcode_png : "res/ui/icon/qrcode.png",
    icon_gold_png : "res/ui/icon/gold.png",
    icon_acer_png : "res/ui/icon/acer.png",
    icon_face_1_png : "res/ui/icon/face_1.png",
    icon_face_1_m_png : "res/ui/icon/face_1_m.png",
    icon_face_2_png : "res/ui/icon/face_2.png",
    icon_face_2_m_png : "res/ui/icon/face_2_m.png",
    icon_face_3_png : "res/ui/icon/face_3.png",
    icon_face_3_m_png : "res/ui/icon/face_3_m.png",
    icon_face_4_png : "res/ui/icon/face_4.png",
    icon_face_4_m_png : "res/ui/icon/face_4_m.png",
    icon_face_5_png : "res/ui/icon/face_5.png",
    icon_face_5_m_png : "res/ui/icon/face_5_m.png",
    icon_face_6_png : "res/ui/icon/face_6.png",
    icon_face_6_m_png : "res/ui/icon/face_6_m.png",
    icon_face_7_png : "res/ui/icon/face_7.png",
    icon_face_7_m_png : "res/ui/icon/face_7_m.png",
    icon_face_8_png : "res/ui/icon/face_8.png",
    icon_face_8_m_png : "res/ui/icon/face_8_m.png",
    icon_face_9_png : "res/ui/icon/face_9.png",
    icon_face_9_m_png : "res/ui/icon/face_9_m.png",
    icon_face_10_png : "res/ui/icon/face_10.png",
    icon_face_10_m_png : "res/ui/icon/face_10_m.png",
    icon_face_mask_png : "res/ui/icon/face_mask.png",
    icon_face_border_png : "res/ui/icon/face_border.png",
    //comsys
    comsys_arrow_png : "res/ui/comsys/arrow.png",
    comsys_game_match_00_png : "res/ui/comsys/game_match_00.png",
    comsys_war_04_png : "res/ui/comsys/war_04.png",
    comsys_com_4_png : "res/ui/comsys/com_4.png",
    comsys_com_4_plist : "res/ui/comsys/com_4.plist",
    comsys_com_6_png : "res/ui/comsys/com_6.png",
    comsys_com_6_plist : "res/ui/comsys/com_6.plist",
    comsys_com_7_png : "res/ui/comsys/com_7.png",
    comsys_com_7_plist : "res/ui/comsys/com_7.plist",
    comsys_com_8_png : "res/ui/comsys/com_8.png",
    comsys_com_8_plist : "res/ui/comsys/com_8.plist",
    comsys_com_9_png : "res/ui/comsys/com_9.png",
    comsys_com_9_plist : "res/ui/comsys/com_9.plist",
    comsys_com_10_png : "res/ui/comsys/com_10.png",
    comsys_com_10_plist : "res/ui/comsys/com_10.plist",
    comsys_com_12_png : "res/ui/comsys/com_12.png",
    comsys_com_12_plist : "res/ui/comsys/com_12.plist",
    comsys_com_13_png : "res/ui/comsys/com_13.png",
    comsys_com_13_plist : "res/ui/comsys/com_13.plist",
    comsys_game_0_png : "res/ui/comsys/game_0.png",
    comsys_game_0_plist : "res/ui/comsys/game_0.plist",
    comsys_game_1_png : "res/ui/comsys/game_1.png",
    comsys_game_1_plist : "res/ui/comsys/game_1.plist",
    comsys_game_2_png : "res/ui/comsys/game_2.png",
    comsys_game_2_plist : "res/ui/comsys/game_2.plist",
    //currency
    currency_currency_0_png : "res/ui/currency/currency_0.png",
    currency_currency_0_plist : "res/ui/currency/currency_0.plist",
    currency_currency_1_png : "res/ui/currency/currency_1.png",
    currency_currency_1_plist : "res/ui/currency/currency_1.plist",
    //function
    function_firstflush_0_png : "res/ui/function/firstflush_0.png",
    function_firstflush_0_plist : "res/ui/function/firstflush_0.plist",
    function_extension_0_png : "res/ui/function/extension_0.png",
    function_extension_0_plist : "res/ui/function/extension_0.plist",
    function_popup_0_png : "res/ui/function/popup_0.png",
    function_popup_0_plist : "res/ui/function/popup_0.plist",
    function_popup_1_png : "res/ui/function/popup_1.png",
    function_popup_1_plist : "res/ui/function/popup_1.plist",
    function_red_0_png : "res/ui/function/red_0.png",
    function_red_0_plist : "res/ui/function/red_0.plist",
    function_shop_0_png : "res/ui/function/shop_0.png",
    function_shop_0_plist : "res/ui/function/shop_0.plist",
    function_red_00_png : "res/ui/function/red_00.png",
    function_turntable_05_png : "res/ui/function/turntable_05.png",
    function_limitopen_05_png : "res/ui/function/limitopen_05.png",
    //landing
    landing_landing_0_png : "res/ui/landing/landing_0.png",
    landing_landing_0_plist : "res/ui/landing/landing_0.plist",
    landing_landing_1_png : "res/ui/landing/landing_1.png",
    landing_landing_1_plist : "res/ui/landing/landing_1.plist",
    //lobby
    ui_loading_xz_png : "res/ui/loading_xz.png",
    ui_scrollbar_png : "res/ui/scrollbar.png",
    lobby_lobby_0_png : "res/ui/lobby/lobby_0.png",
    lobby_lobby_0_plist : "res/ui/lobby/lobby_0.plist",
    lobby_vip_png : "res/ui/lobby/vip.png",
    lobby_vip_plist : "res/ui/lobby/vip.plist",
    //animation
    animation_red_1_png : "res/ui/animation/red/red_1.png",
    animation_red_1_plist : "res/ui/animation/red/red_1.plist",
    animation_red_2_png : "res/ui/animation/red/red_2.png",
    animation_red_2_plist : "res/ui/animation/red/red_2.plist",
    animation_red_10_01_png : "res/ui/animation/red/red_10_01.png",
    animation_red_11_01_png : "res/ui/animation/red/red_11_01.png",
    animation_red_12_01_png : "res/ui/animation/red/red_12_01.png",
    //spine
    ui_spine_dismond_png : "res/ui/spine/dismond.png",
    ui_spine_sichuan_girl_png : "res/ui/spine/sichuan_girl.png",
    ui_spine_jinbi_png : "res/ui/spine/jinbi.png",
    ui_spine_kuaisukaishi_png : "res/ui/spine/kuaisukaishi.png",
    ui_spine_yuezhang_png : "res/ui/spine/yuezhang.png",
    //json
    res_advertising_json : "res/advertising.json",
    res_agentmaildialog_ui_json : "res/agentmaildialog_ui.json",
    res_calldialog_ui_json : "res/calldialog_ui.json",
    res_comsys_item_1_json : "res/comsys_item_1.json",
    res_comsys_item_2_json : "res/comsys_item_2.json",
    res_comsys_room_json : "res/comsys_room.json",
    res_comsys_create_json : "res/comsys_create.json",
    res_comsys_war_json : "res/comsys_war.json",
    res_dialog_ui_json : "res/dialog_ui.json",
    res_downloader_new_json : "res/downloader_new.json",
    res_facedialog_ui_json : "res/facedialog_ui.json",
    res_forgetpwd_ui_json : "res/forgetpwd_ui.json",
    res_first_flush_ui_json : "res/first_flush_ui.json",
    res_landlords_competition_json : "res/landlords_competition.json",
    res_landlords_competition_cancel_json : "res/landlords_competition_cancel.json",
    res_landlords_competition_enroll_json : "res/landlords_competition_enroll.json",
    res_lobby_json : "res/lobby.json",
    res_login_json : "res/login.json",
    res_mailcenter_json : "res/mailcenter.json",
    res_maildialog_ui_json : "res/maildialog_ui.json",
    res_noticebar_ui_json : "res/noticebar_ui.json",
    res_noticedialog_ui_json : "res/noticedialog_ui.json",
    res_personal_json : "res/personal.json",
    res_preloading_json : "res/preloading.json",
    res_prizes_json : "res/prizes.json",
    res_ranking_list_json : "res/ranking_list.json",
    res_rechargecenter_json : "res/rechargecenter.json",
    res_rechargecenter_gold_json : "res/rechargecenter_gold.json",
    res_rechargecenter_red_json : "res/rechargecenter_red.json",
    res_rechargecenter_payment_json : "res/rechargecenter_payment.json",
    res_rechargecenter_prompt_json : "res/rechargecenter_prompt.json",
    res_redpacket_open_json : "res/redpacket_open.json",
    res_redpacket_ui_json : "res/redpacket_ui.json",
    res_setdialog_ui_json : "res/setdialog_ui.json",
    res_sign_ui_json : "res/sign_ui.json",
    res_turntable_json : "res/turntable.json",
    res_usercenter_json : "res/usercenter.json",
    res_usercenter_acc_ui_json : "res/usercenter_acc_ui.json",
    res_usercenter_real_name_json : "res/usercenter_real_name.json",
    res_visitordialog_ui_json : "res/visitordialog_ui.json",
    res_welfare_center_json : "res/welfare_center.json",
    res_limitopen_json : "res/limitopen.json",
    //animation
    res_ation_firstflush_json : "res/ation_firstflush.json",
    res_ation_shopgold_0_json : "res/ation_shopgold_0.json",
    res_ation_shopgold_1_json : "res/ation_shopgold_1.json",
    res_ation_shopgold_2_json : "res/ation_shopgold_2.json",
    res_ation_shopgold_3_json : "res/ation_shopgold_3.json",
    res_ation_shopgold_4_json : "res/ation_shopgold_4.json",
    res_ation_shopgold_5_json : "res/ation_shopgold_5.json",
    res_ation_shopgold_6_json : "res/ation_shopgold_6.json",
    res_ation_shopgold_7_json : "res/ation_shopgold_7.json"
};
modulelobby.res_entry = {
    ui_company_logo_png : "res/ui/company_logo.jpg",
    ui_green_bulletin_png : "res/ui/green_bulletin.png",
    updatepage_json : "res/updatepage.json",
    loading_bg_png : "res/ui/bg.jpg",
    loading_loading_png : "res/ui/loading.jpg",
    loading_loading_t_png : "res/ui/loading_t.png",
    loading_loading_tbg_png : "res/ui/loading_tbg.png",
    loading_json : "res/loading.json"
};
modulelobby.g_resources = [];
for (var i in modulelobby.res_entry) {
    modulelobby.g_resources.push(modulelobby.res_entry[i]);
}

modulelobby.g_res_hot = [];
for (var k in modulelobby.res) {
    modulelobby.g_res_hot.push(modulelobby.res[k]);
}